[project]
name = "sandrone"
version = "1.2.0"
description = "Python utility bot"
readme = "README.md"
authors = [
    { name = "Clove Twilight", email = "admin@doughmination.win" }
]
requires-python = ">=3.14"
dependencies = [
    "colorful>=0.5.8",
    "discord-py>=2.7.1",
    "pluralkit>=1.2.1",
    "pygithub>=2.9.1",
    "python-dotenvx>=2.0.0",
    "qrcode[pil]>=8.2",
    "ruff>=0.16.3",
    "toml>=0.10.2",
    "ty>=0.0.72",
    "watchfiles>=1.2.0",
    "wikipedia-api>=0.15.0",
]

[tool.uv]
package=false
